// global
export default {
    FETCH_SAVED_DATA: "FETCH_SAVED_DATA",
    DATA_FETCHED: "DATA_FETCHED",
    TOGGLE_MAIN_DRAWER: "TOGGLE_MAIN_DRAWER",    
    INIT_LOADING: "INIT_LOADING",
    END_LOADING: "END_LOADING",
    SHOW_ALERT: "SHOW_ALERT",
    HIDE_ALERT: "HIDE_ALERT"
}