// global
export default {
    FETCH_SAVED_DATA: "FETCH_SAVED_DATA",
    DATA_FETCHED: "DATA_FETCHED",
    TOGGLE_MAIN_DRAWER: "TOGGLE_MAIN_DRAWER",
    CREATE_NEW: "CREATE_NEW",
    CREATE_NEW_CLOSE: "CREATE_NEW_CLOSE"
}