export default {
    FETCH_LYRICS: "FETCH_LYRICS",
    LYRICS_FETCHED: "LYRICS_FETCHED",
    SAVED_LYRICS_FETCHED: "SAVED_LYRICS_FETCHED",
    SAVING_LYRICS : "SAVING_LYRICS",
    LYRICS_SAVED : "LYRICS_SAVED"
}