export default {
    FETCH_SAVED_DATA: "FETCH_SAVED_DATA",
    DATA_FETCHED: "DATA_FETCHED",
    SET_FAVORITE: "SET_FAVORITE",
    SET_FAVORITE_RESPONSE: "SET_FAVORITE_RESPONSE",
    DELETE_LYRICS: "DELETE_LYRICS",
    DELETE_LYRICS_RESPONSE: "DELETE_LYRICS_RESPONSE"
}