export default {
    FETCH_SAVED_DATA: "FETCH_SAVED_DATA",
    DATA_FETCHED: "DATA_FETCHED",
    SET_FAVORITE: "SET_FAVORITE",
    SET_FAVORITE_RESPONSE: "SET_FAVORITE_RESPONSE",
    DELETE_SONG: "DELETE_SONG",
    DELETE_SONG_RESPONSE: "DELETE_SONG_RESPONSE"    
}